name:                kubernetes-client-tools-unofficial
version:             0.1.0.0
github:              "frincon/kubernetes-client-tools-unofficial"
license:             Apache-2.0
author:              "Fernando Rincon Martin"
maintainer:          "f.rincon@protonmal.com"
copyright:           "2019 Fernando Rincon Martin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Unofficial tools for using kubernetes with haskell
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/frincon/kubernetes-client-tools-unofficial#readme>

ghc-options:
- -Wall
dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - async
  - bytestring
  - directory
  - filepath
  - http-client
  - http-mock
  - http-types
  - interpolate
  - kubernetes-client
  - kubernetes-client-core >= 0.1.0.2
  - network
  - placeholders
  - random
  - text
  - time
  - wai

tests:
  kubernetes-client-toos-unofficial-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - kubernetes-client-tools-unofficial
    - hspec
    - http-types
    - kubernetes-client
    - kubernetes-client-core >= 0.1.0.2
    - microlens
    - placeholders
    - QuickCheck
    - text
    - time

executables:
  leader-election-example:
    main:                Main.hs
    source-dirs:         app/leader-election-example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kubernetes-client >= 0.1.0.2
    - kubernetes-client-core >= 0.1.0.2
    - kubernetes-client-tools-unofficial
    - text
    - tls

  operator-example:
    main:                Main.hs
    source-dirs:         app/operator-example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - directory
    - file-embed
    - kubernetes-client >= 0.1.0.2
    - kubernetes-client-core >= 0.1.0.2
    - kubernetes-client-tools-unofficial
    - stm
    - text
    - tls
    - yaml